src/CqrsEventSourcingDemo.Web/Controllers/Cafe/ChefController.cs
using System;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using CqrsEventSourcingDemo.Command.Tab;
using CqrsEventSourcingDemo.Event.Tab;
using CqrsEventSourcingDemo.ReadModel.Tab;
using CqrsEventSourcingDemo.Web.Controllers.Attributes;
using Reusables.Cqrs;

namespace CqrsEventSourcingDemo.Web.Controllers.Cafe
{
    [IncludeLayoutData]
    public class ChefController : BaseController
    {
        private readonly IRequestDispatcher _dispatcher;

        public ChefController(IRequestDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        public ActionResult Index()
        {
            var todoLists = _dispatcher.DispatchQuery(new GetTodoLists());

            return View(todoLists);
        }

        public ActionResult MarkPrepared(Guid tabId, FormCollection form)
        {
            var servedItemsPattern = new Regex("^prepared_\\d+_(\\d+)$", RegexOptions.Compiled);
            var servedMenuNumbers =
                form.AllKeys
                    .Where(key => servedItemsPattern.IsMatch(key))
                    .Where(key => form[key] != "false")
                    .Select(key => servedItemsPattern.Match(key))
                    .Select(match => match.Groups[1].Value)
                    .Select(int.Parse)
                    .ToList();

            _dispatcher.DispatchCommand(
                new MarkFoodPrepared
                {
                    TabId = tabId,
                    MenuNumbers = servedMenuNumbers
                });

            return RedirectToAction("Index");
        }
    }
}

src/CqrsEventSourcingDemo.Web/Controllers/Cafe/TabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using CqrsEventSourcingDemo.Command.Tab;
using CqrsEventSourcingDemo.Event.Tab;
using CqrsEventSourcingDemo.ReadModel.Tab;
using CqrsEventSourcingDemo.Web.Controllers.Attributes;
using CqrsEventSourcingDemo.Web.Models;
using Reusables.Cqrs;

namespace CqrsEventSourcingDemo.Web.Controllers.Cafe
{
    [IncludeLayoutData]
    public class TabController : BaseController
    {
        private readonly IRequestDispatcher _dispatcher;

        public TabController(IRequestDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        public ActionResult Open()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Open(OpenTab command)
        {
            _dispatcher.DispatchCommand(command);

            return RedirectToAction("Order", new {id = command.TableNumber});
        }

        public ActionResult Order(int id)
        {
            return View(new OrderModel {Items = StaticData.Menu.Select(CreateOrderLineItem).ToList()});
        }

        [HttpPost]
        public ActionResult Order(int id, OrderModel orderModel)
        {
            _dispatcher.DispatchCommand(new PlaceOrder
                                        {
                                            TabId = _dispatcher.DispatchQuery(new TabIdForTable {TableNumber = id}),
                                            Items = OrderedItems(orderModel).ToList()
                                        });

            return RedirectToAction("Status", new {id = id});
        }

        public ActionResult Status(int id)
        {
            var tabStatus = _dispatcher.DispatchQuery(new TabForTable {TableNumber = id});

            return View(tabStatus);
        }

        public ActionResult MarkServed(int id, FormCollection form)
        {
            var tabId = _dispatcher.DispatchQuery(new TabIdForTable {TableNumber = id});

            var servedItemsPattern = new Regex("^served_\\d+_(\\d+)$", RegexOptions.Compiled);
            var servedMenuNumbers = form.AllKeys
                                        .Where(key => servedItemsPattern.IsMatch(key))
                                        .Where(key => form[key] != "false")
                                        .Select(key => servedItemsPattern.Match(key))
                                        .Select(match => match.Groups[1].Value)
                                        .Select(int.Parse)
                                        .ToList();

            DispatchCommands(tabId, servedMenuNumbers);

            return RedirectToAction("Status", new {id = id});
        }

        public ActionResult Close(int id)
        {
            return View(new CloseModel {TableNumber = id});
        }

        [HttpPost]
        public ActionResult Close(CloseModel model)
        {
            var tabId = _dispatcher.DispatchQuery(new TabIdForTable {TableNumber = model.TableNumber});

            _dispatcher.DispatchCommand(
                new CloseTab
                {
                    TabId = tabId,
                    AmountPaid = model.AmountPaid
                });

            return RedirectToAction("Index", "Home");
        }

        private static IEnumerable<OrderedItem> OrderedItems(OrderModel orderModel)
        {
            return orderModel.Items
                             .Where(x => x.NumberToOrder > 0)
                             .SelectMany(CreateOrderedItemsFromLineItem);
        }

        private static IEnumerable<OrderedItem> CreateOrderedItemsFromLineItem(OrderLineItem lineItem)
        {
            var menuItem = StaticData.Menu.Single(item => item.MenuNumber == lineItem.MenuNumber);

            return Enumerable.Range(0, lineItem.NumberToOrder)
                             .Select(i => CreateOrderedItem(lineItem.MenuNumber, menuItem));
        }

        private static OrderedItem CreateOrderedItem(int menuNumber, MenuItem menuItem)
        {
            return new OrderedItem
                   {
                       MenuNumber = menuNumber,
                       Description = menuItem.Description,
                       IsDrink = menuItem.IsDrink,
                       Price = menuItem.Price
                   };
        }

        private static OrderLineItem CreateOrderLineItem(MenuItem menuItem)
        {
            return new OrderLineItem
                   {
                       MenuNumber = menuItem.MenuNumber,
                       Description = menuItem.Description,
                       NumberToOrder = 0
                   };
        }

        private void DispatchCommands(Guid tabId, List<int> servedMenuNumbers)
        {
            var isDrinkLookup = StaticData.Menu.ToDictionary(menuItem => menuItem.MenuNumber, menuItem => menuItem.IsDrink);

            DispatchMarkDrinksServedCommand(tabId, servedMenuNumbers, isDrinkLookup);

            DispatchMarkFoodServedCommand(tabId, servedMenuNumbers, isDrinkLookup);
        }

        private void DispatchMarkDrinksServedCommand(Guid tabId, List<int> servedMenuNumbers, Dictionary<int, bool> isDrinkLookup)
        {
            var drinks = servedMenuNumbers.Where(item => isDrinkLookup[item]).ToList();

            if (drinks.Any())
                _dispatcher.DispatchCommand(
                    new MarkDrinksServed
                    {
                        TabId = tabId,
                        MenuNumbers = servedMenuNumbers
                    });
        }

        private void DispatchMarkFoodServedCommand(Guid tabId, List<int> servedMenuNumbers, Dictionary<int, bool> isDrinkLookup)
        {
            var food = servedMenuNumbers.Where(item => !isDrinkLookup[item]).ToList();

            if (food.Any())
                _dispatcher.DispatchCommand(
                    new MarkFoodServed
                    {
                        TabId = tabId,
                        MenuNumbers = food
                    });
        }
    }
}

src/CqrsEventSourcingDemo.Web/Controllers/Cafe/WaitStaffController.cs
using System.Web.Mvc;
using CqrsEventSourcingDemo.ReadModel.Tab;
using CqrsEventSourcingDemo.Web.Controllers.Attributes;
using Reusables.Cqrs;

namespace CqrsEventSourcingDemo.Web.Controllers.Cafe
{
    [IncludeLayoutData]
    public class WaitStaffController : BaseController
    {
        private readonly IRequestDispatcher _dispatcher;

        public WaitStaffController(IRequestDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        public ActionResult Todo(string id)
        {
            var tabItems = _dispatcher.DispatchQuery(new TodoListForWaiter {StaffId = id});

            ViewBag.Waiter = id;

            return View(tabItems);
        }
    }
}

src/CqrsEventSourcingDemo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CQRS/ES Demo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CQRS/ES Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Open Tab", "Open", "Tab")</li>
                    <li>@Html.ActionLink("Chef Todo List", "Index", "Chef")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-sm-3">
                <div class="well">
                    <ul class="nav nav-stacked">
                        <li class="text-uppercase">Wait Staff Todo Lists</li>
                        @foreach (string staff in ViewBag.WaitStaff)
                        {
                            <li>@Html.ActionLink(staff, "Todo", "WaitStaff", new {id = @staff}, null)</li>
                        }
                        <li class="text-uppercase">Open Tabs</li>
                        @foreach (int tableNumber in ViewBag.ActiveTables)
                        {
                            <li>@Html.ActionLink(tableNumber.ToString(), "Status", "Tab", new {id = tableNumber}, null)</li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-sm-9">
                @RenderBody()
            </div>
        </div>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - A CQRS/ES Demo Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>